name: CI

# Avoid duplicate builds for pull requests, allow manual trigger.
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false

      - name: Get sources
        uses: actions/checkout@v2

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: ./third_party/*
          key: ${{ runner.os }}-${{ github.workspace }}-deps-${{ hashFiles('./third_party/*') }}

      - run: make
      - run: make test-depend
      - run: make test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: objectbox-generator-${{ runner.os }}
          path: objectbox-generator*
